import type { Signal, Holding } from "./types";

export const MOCK_SIGNALS: Signal[] = [
  {
    id: "nvda-1",
    ticker: "NVDA",
    company: "NVIDIA Corporation",
    exchange: "NASDAQ",
    price: 172.35,
    change: 4.82,
    changePercent: 2.88,
    call: "BUY",
    conviction: 92,
    horizon: "2–4 weeks",
    entry: 172.0,
    target: 210.0,
    stop: 162.0,
    riskReward: "1:3.8",
    why: "Convergence of insider accumulation, Street upgrades, and unusual call activity ahead of GTC announcements.",
    tags: ["INSIDER BUY", "UPGRADE", "CALL FLOW"],
    signals: [
      {
        type: "INSIDER_BUY",
        title: "Director buys $2.4M in shares",
        detail: "Mark Stevens purchased 14,000 shares at $171.50 avg — largest insider buy in 8 months.",
        sentiment: "positive",
      },
      {
        type: "UPGRADE",
        title: "KeyBanc upgrades to Overweight",
        detail: "Price target raised from $180 → $220. Cites datacenter demand acceleration.",
        sentiment: "positive",
      },
      {
        type: "OPTIONS_FLOW",
        title: "$12M in June 200C sweeps",
        detail: "Block trades across multiple exchanges, bullish premium surge.",
        sentiment: "positive",
      },
      {
        type: "NEWS",
        title: "GTC keynote catalyst",
        detail: "Jensen Huang keynote in 2 weeks — expected Blackwell Ultra announcement.",
        sentiment: "positive",
      },
    ],
    sparkline: [165, 167, 166, 168, 170, 169, 171, 170, 172, 172.35],
    timestamp: new Date().toISOString(),
  },
  {
    id: "aapl-1",
    ticker: "AAPL",
    company: "Apple Inc.",
    exchange: "NASDAQ",
    price: 198.11,
    change: 1.23,
    changePercent: 0.62,
    call: "BUY",
    conviction: 85,
    horizon: "1–3 months",
    entry: 197.0,
    target: 230.0,
    stop: 188.0,
    riskReward: "1:3.7",
    why: "Services revenue acceleration and AI integration into iOS ecosystem driving re-rating.",
    tags: ["EARNINGS", "UPGRADE"],
    signals: [
      {
        type: "EARNINGS",
        title: "Q2 beat on services revenue",
        detail: "Services hit $24.2B, +14% YoY — highest margin segment growing fastest.",
        sentiment: "positive",
      },
      {
        type: "UPGRADE",
        title: "Morgan Stanley reiterates Overweight",
        detail: "PT raised to $240 citing Apple Intelligence monetization path.",
        sentiment: "positive",
      },
    ],
    sparkline: [192, 193, 195, 194, 196, 197, 196, 198, 197, 198.11],
    timestamp: new Date().toISOString(),
  },
  {
    id: "tsla-1",
    ticker: "TSLA",
    company: "Tesla, Inc.",
    exchange: "NASDAQ",
    price: 248.42,
    change: -8.15,
    changePercent: -3.18,
    call: "REDUCE",
    conviction: 78,
    horizon: "1–2 weeks",
    entry: undefined,
    target: undefined,
    stop: undefined,
    riskReward: undefined,
    why: "Insider selling accelerates as delivery numbers disappoint and competition intensifies.",
    tags: ["INSIDER SELL", "DOWNGRADE"],
    signals: [
      {
        type: "INSIDER_SELL",
        title: "CFO sells $18M in shares",
        detail: "Vaibhav Taneja sold 72,000 shares via 10b5-1 plan — 3rd sale this quarter.",
        sentiment: "negative",
      },
      {
        type: "DOWNGRADE",
        title: "Wells Fargo cuts to Underweight",
        detail: "PT lowered to $200. Margin compression concerns from price cuts.",
        sentiment: "negative",
      },
    ],
    sparkline: [260, 258, 255, 257, 253, 250, 252, 249, 248, 248.42],
    timestamp: new Date().toISOString(),
  },
  {
    id: "msft-1",
    ticker: "MSFT",
    company: "Microsoft Corporation",
    exchange: "NASDAQ",
    price: 442.58,
    change: 2.31,
    changePercent: 0.52,
    call: "BUY",
    conviction: 88,
    horizon: "1–3 months",
    entry: 440.0,
    target: 500.0,
    stop: 420.0,
    riskReward: "1:3.0",
    why: "Azure AI revenue inflection with Copilot enterprise adoption accelerating.",
    tags: ["EARNINGS", "OPTIONS FLOW"],
    signals: [
      {
        type: "EARNINGS",
        title: "Azure growth re-accelerates to 33%",
        detail: "AI services contributing 8 points of growth — demand exceeding supply.",
        sentiment: "positive",
      },
      {
        type: "OPTIONS_FLOW",
        title: "Heavy Sept 480C accumulation",
        detail: "$8.2M in bullish flow, institutional positioning ahead of next earnings.",
        sentiment: "positive",
      },
    ],
    sparkline: [435, 437, 436, 438, 440, 439, 441, 442, 441, 442.58],
    timestamp: new Date().toISOString(),
  },
  {
    id: "amd-1",
    ticker: "AMD",
    company: "Advanced Micro Devices",
    exchange: "NASDAQ",
    price: 164.89,
    change: 0.45,
    changePercent: 0.27,
    call: "WATCH",
    conviction: 62,
    horizon: "Earnings Jun 29",
    entry: undefined,
    target: undefined,
    stop: undefined,
    riskReward: undefined,
    why: "Earnings in 11 days — AI GPU market share thesis needs validation from MI300X numbers.",
    tags: ["EARNINGS", "8-K"],
    signals: [
      {
        type: "EARNINGS",
        title: "Q2 earnings Jun 29 AMC",
        detail: "Street expects $0.92 EPS, $5.8B revenue. MI300X datacenter guidance is the key.",
        sentiment: "neutral",
      },
      {
        type: "SEC_FILING",
        title: "8-K: New $6B buyback program",
        detail: "Board approved additional share repurchase authorization.",
        sentiment: "positive",
      },
    ],
    sparkline: [162, 163, 164, 163, 165, 164, 163, 165, 164, 164.89],
    timestamp: new Date().toISOString(),
  },
];

export const MOCK_HOLDINGS: Holding[] = [
  {
    ticker: "NVDA",
    company: "NVIDIA Corporation",
    shares: 50,
    avgCost: 155.0,
    currentPrice: 172.35,
    change: 4.82,
    changePercent: 2.88,
    totalValue: 8617.5,
    pnl: 867.5,
    pnlPercent: 11.19,
    hasActiveSignal: true,
    sparkline: [165, 167, 166, 168, 170, 169, 171, 170, 172, 172.35],
  },
  {
    ticker: "AAPL",
    company: "Apple Inc.",
    shares: 30,
    avgCost: 185.0,
    currentPrice: 198.11,
    change: 1.23,
    changePercent: 0.62,
    totalValue: 5943.3,
    pnl: 393.3,
    pnlPercent: 7.09,
    hasActiveSignal: true,
    sparkline: [192, 193, 195, 194, 196, 197, 196, 198, 197, 198.11],
  },
  {
    ticker: "MSFT",
    company: "Microsoft Corporation",
    shares: 15,
    avgCost: 410.0,
    currentPrice: 442.58,
    change: 2.31,
    changePercent: 0.52,
    totalValue: 6638.7,
    pnl: 488.7,
    pnlPercent: 7.94,
    hasActiveSignal: false,
    sparkline: [435, 437, 436, 438, 440, 439, 441, 442, 441, 442.58],
  },
  {
    ticker: "GOOGL",
    company: "Alphabet Inc.",
    shares: 25,
    avgCost: 168.0,
    currentPrice: 178.34,
    change: -0.92,
    changePercent: -0.51,
    totalValue: 4458.5,
    pnl: 258.5,
    pnlPercent: 6.15,
    hasActiveSignal: false,
    sparkline: [175, 176, 177, 178, 177, 179, 178, 179, 178, 178.34],
  },
  {
    ticker: "META",
    company: "Meta Platforms, Inc.",
    shares: 10,
    avgCost: 480.0,
    currentPrice: 505.24,
    change: 3.45,
    changePercent: 0.69,
    totalValue: 5052.4,
    pnl: 252.4,
    pnlPercent: 5.26,
    hasActiveSignal: false,
    sparkline: [498, 500, 502, 501, 503, 504, 503, 505, 504, 505.24],
  },
];

export function getTodayDate(): string {
  return new Date().toLocaleDateString("en-US", {
    weekday: "long",
    month: "long",
    day: "numeric",
  });
}
